import{a as u,S as d,i as l}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g={BASE_URL:"/goit-js-hw-11/",DEV:!1,MODE:"production",PROD:!0,SSR:!1},h="https://pixabay.com/api/",y="YOUR_PIXABAY_API_KEY";u.defaults.baseURL=h;function A(i){return u.get("",{params:{key:y,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data).catch(r=>{throw r})}console.log("ENV",g);console.log("API_KEY",void 0);const p=document.getElementById("gallery"),a=document.getElementById("loader"),L=new d(".gallery a",{captionsData:"alt",captionDelay:200});function _(i){const r=i.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:n,comments:m,downloads:f})=>`
      <li class="card">
        <a href="${o}">
          <img src="${s}" alt="${P(e)}" loading="lazy" />
        </a>
        <div class="meta">
          <span>Likes: ${t}</span>
          <span>Views: ${n}</span>
          <span>Comments: ${m}</span>
          <span>Downloads: ${f}</span>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",r),L.refresh()}function b(){p.innerHTML=""}function E(){a.classList.add("is-visible"),a.setAttribute("aria-hidden","false")}function v(){a.classList.remove("is-visible"),a.setAttribute("aria-hidden","true")}function P(i=""){return String(i).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}const c=document.getElementById("search-form");c.addEventListener("submit",i=>{i.preventDefault();const s=(new FormData(c).get("search-text")||"").trim();if(!s){l.warning({title:"Упс…",message:"Введіть пошукове слово.",timeout:2500,position:"topRight"});return}b(),E(),A(s).then(o=>{const e=Array.isArray(o==null?void 0:o.hits)?o.hits:[];if(e.length===0){l.info({title:"Немає збігів",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"});return}_(e)}).catch(()=>{l.error({title:"Помилка",message:"Сталася помилка під час запиту. Спробуйте пізніше.",timeout:3e3,position:"topRight"})}).finally(()=>{v()})});
//# sourceMappingURL=index.js.map
